services:
  mapping-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - back-tier
  # proxy:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.proxy
  backend-tester:
    build:
      context: .
      dockerfile: Dockerfile.newman
      args:
        TARGET: mapping-backend
    depends_on:
      - mapping-backend
    networks:
      - back-tier

networks:
  front-tier: {}
  back-tier: {}
