# syntax=docker/dockerfile:1
## == build == ##
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

WORKDIR /app/M2MT.Mapping

COPY CS/M2MT.Mapping/*.csproj ./
RUN dotnet restore

WORKDIR /app

COPY CS ./
RUN dotnet publish -c Release -o out

## == Build runtime image == ##
FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app

COPY --from=build-env /app/out .

COPY CS/test-env.json ./appsettings.json

EXPOSE 7028

ENTRYPOINT ["dotnet", "M2MT.Mapping.dll"]
